/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.Recomendar;
import modelo.Producto;
import modelo.Usuario;

/**
 *
 * @author Jhon
 */
public class CuentaUsuarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form CuentaUsuarioPanel
     */
    FramePrincipal frame;
    Usuario usuario;
    Recomendar recomendar;
    DefaultTableModel modelo;
    public CuentaUsuarioPanel(FramePrincipal frame) {
        this.frame = frame;
        frame.agregarPanel(1, this);
        this.usuario = frame.getUsuario();
        initComponents();
        setBackground(Color.white);
        //nombreField.setText(usuario.getNombreUsuario());
        //EdadField.setText(String.valueOf(usuario.getEdad()));
        //sexoField.setText(usuario.getSexo().toString());
        //ocupacionField.setText(usuario.getOcupacion());
    }
    
    public void setNombreUsuario(String nombre){
        nombreField.setText(nombre);
    }
    
    public void setEdadUsuario(int edad){
        EdadField.setText(String.valueOf(edad));
    }    

    public void setSexoUsuario(char sex){
        sexoField.setText(Character.toString(sex));
    }

    public void setOcupacionUsuario(String ocupacion){
        ocupacionField.setText(ocupacion);
    }

    public void TablaRecomendadosUsuario(Usuario user){
        recomendar = new Recomendar();
        List<Producto> listaDeRecomendados = new ArrayList<Producto>();
        listaDeRecomendados = recomendar.generarRecomendacion(user);
        setTabla(listaDeRecomendados);
    }
    
    public void setTabla(List<Producto> ProductosRecomendados){
        modelo = (DefaultTableModel) recomendadosTable.getModel();
        int size = modelo.getRowCount();
        for (int i = 0; i < size; i++) {
            modelo.removeRow(0);
        } 
        String aux[];
        for (int j = 0; j < ProductosRecomendados.size(); j++) {
            aux = new String[7];
            aux[0] = ProductosRecomendados.get(j).getProductoID().toString(); 
            aux[1] = ProductosRecomendados.get(j).getNombreProducto();
            aux[2] = String.valueOf(ProductosRecomendados.get(j).getPrecioProducto()); 
            aux[3] = ProductosRecomendados.get(j).getDescripcionProducto();
            aux[4] = ProductosRecomendados.get(j).getCategoriaProducto();
            aux[5] = ProductosRecomendados.get(j).getSubcategoriaProducto();
            aux[6] = String.valueOf(ProductosRecomendados.get(j).getCantidadDisponible());
            modelo.addRow(aux);
         }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        EdadField = new javax.swing.JTextField();
        sexoField = new javax.swing.JTextField();
        ocupacionField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recomendadosTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        verComprasButton = new javax.swing.JButton();
        VerConsultasButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TU CUENTA DE USUARIO:");

        jLabel2.setText("Nombre:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Sexo:");

        jLabel7.setText("Ocupacion:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tus Ultimas Compras");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tus Ultimas Consultas");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Productos recomendados para ti");

        recomendadosTable.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        recomendadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Producto", "Nombre", "Precio", "Descripcion", "Categoria", "Subcategoria", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(recomendadosTable);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Bestshop_Logo2.jpg"))); // NOI18N

        verComprasButton.setText("Ver Ultimas Compras");
        verComprasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verComprasButtonActionPerformed(evt);
            }
        });

        VerConsultasButton.setText("Ver Ultimas Consultas");
        VerConsultasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerConsultasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(verComprasButton)
                            .addComponent(VerConsultasButton)
                            .addComponent(jLabel8))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(361, 361, 361)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(sexoField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ocupacionField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(EdadField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(EdadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ocupacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sexoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verComprasButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(VerConsultasButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verComprasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verComprasButtonActionPerformed
        frame.setTablaComprasUsuario();
        frame.swap(4); // Ir al panel de ultimas compras
    }//GEN-LAST:event_verComprasButtonActionPerformed

    private void VerConsultasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerConsultasButtonActionPerformed
        frame.setTablaConsultaUsuario();
        frame.swap(5); //Ir al panel Ultimas consultas
    }//GEN-LAST:event_VerConsultasButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EdadField;
    private javax.swing.JButton VerConsultasButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField ocupacionField;
    private javax.swing.JTable recomendadosTable;
    private javax.swing.JTextField sexoField;
    private javax.swing.JButton verComprasButton;
    // End of variables declaration//GEN-END:variables
}
