/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Usuario;


/**
 *
 * @author Jhon
 */
public class FramePrincipal extends javax.swing.JFrame {

    Usuario usuario;
    JPanel panels[] = new JPanel[6];
    
    public FramePrincipal() {
        usuario = new Usuario();
        
        LoginPanel login = new LoginPanel(this);        // Panel 0
        login.setBounds(0,0, 720, 470);
        agregarPanel(0,login);
        login.setVisible(true);
        
        CuentaUsuarioPanel cuentausuario = new CuentaUsuarioPanel(this); // Panel 1
        cuentausuario.setBounds(0,0, 720, 470);
        agregarPanel(1,cuentausuario);
        cuentausuario.setVisible(false);
        
        ProductosPanel productosPanel = new ProductosPanel(this); // Panel 2
        productosPanel.setBounds(0,0, 720, 470);
        agregarPanel(2,productosPanel);
        productosPanel.setVisible(false);
        
        CarroComprasPanel carrocompras = new CarroComprasPanel(this); // Panel 3
        carrocompras.setBounds(0,0, 720, 470);
        agregarPanel(3,carrocompras);
        carrocompras.setVisible(false);
        
        ultimasComprasPanel ultimasCompras = new ultimasComprasPanel(this);// Panel 4
        ultimasCompras.setBounds(0,0, 720, 470);
        agregarPanel(4,ultimasCompras);
        ultimasCompras.setVisible(false);
        
        UltimasConsultasPanel ultimasConsultas = new UltimasConsultasPanel(this);// Panel 5
        ultimasConsultas.setBounds(0,0, 720, 470);
        agregarPanel(5,ultimasConsultas);
        ultimasConsultas.setVisible(false);
        
        
        this.add(login);
        this.add(cuentausuario);
        this.add(productosPanel);
        this.add(carrocompras);
        this.add(ultimasCompras);
         this.add(ultimasConsultas);
        
        
        initComponents();
        jMenuBar1.setVisible(false);
        setResizable(false);
        setLocationRelativeTo(null);
        this.setBackground(Color.white);
       
    }
    
    public void swap(int n) {
        for (int i = 0; i < panels.length; i++) {
            panels[i].setVisible(false);
        }
        panels[n].setVisible(true);
        if (n > 0) {
            jMenuBar1.setVisible(true);
        } else {
            jMenuBar1.setVisible(false);
        }
    }

    public void agregarPanel(int n, JPanel panel) {
        panels[n] = panel;
    }   
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
       
        CuentaUsuarioPanel auxcuentausuario = (CuentaUsuarioPanel) panels[1];
        auxcuentausuario.setNombreUsuario(usuario.getNombreUsuario());
        auxcuentausuario.setEdadUsuario(usuario.getEdad());
        auxcuentausuario.setSexoUsuario(usuario.getSexo());
        auxcuentausuario.setOcupacionUsuario(usuario.getOcupacion());
        //jMenuBar1.setVisible(true);
    }
    
    public Usuario getUsuario() {
        return usuario;
    }
    
    public void setTablaConsultaUsuario(){
       UltimasConsultasPanel auxUltimasConsultas = (UltimasConsultasPanel) panels[5];
       auxUltimasConsultas.llenarTablaConsultas(usuario);
    }

    public void setTablaComprasUsuario(){
       ultimasComprasPanel auxUltimasComprasPanel = (ultimasComprasPanel) panels[4];
       auxUltimasComprasPanel.llenarTablaCompras(usuario);
    }    

    public void setTablaProductos(){
       ProductosPanel auxProductos = (ProductosPanel) panels[2];
       auxProductos.llenarTablaProductos();
    }    
    
     public void setTablaRecomendadosUsuario(){
         CuentaUsuarioPanel auxCuentausuario = (CuentaUsuarioPanel) panels[1];
         auxCuentausuario.TablaRecomendadosUsuario(usuario);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSesionUsuario = new javax.swing.JMenuItem();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemVerProductos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemVerCarroCompras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda de Comercio Electrónico - Best Shop");

        jMenu1.setText("Inicio");

        jMenuItemSesionUsuario.setText("Tu cuenta");
        jMenuItemSesionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSesionUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSesionUsuario);

        jMenuItemCerrarSesion.setText("Cerrar Sesion");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCerrarSesion);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");

        jMenuItemVerProductos.setText("Ver Productos");
        jMenuItemVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerProductosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVerProductos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Carrito de Compras");

        jMenuItemVerCarroCompras.setText("Ver Carro de Compras");
        jMenuItemVerCarroCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerCarroComprasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemVerCarroCompras);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar sesión?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (respuesta == 0) {
            try {
                swap(0);
                jMenuBar1.setVisible(false);
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cerrar sesión.");
            }
        }
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        
        int respuesta = JOptionPane.showConfirmDialog(null, "Realmente Desea Salir?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (respuesta == 0) {
            try {
                System.exit(0);
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al Salir.");
            }
        }        
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerProductosActionPerformed
        setTablaProductos();
        swap(2);
    }//GEN-LAST:event_jMenuItemVerProductosActionPerformed

    private void jMenuItemSesionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSesionUsuarioActionPerformed
        swap(1);
    }//GEN-LAST:event_jMenuItemSesionUsuarioActionPerformed

    private void jMenuItemVerCarroComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerCarroComprasActionPerformed
       swap(3);
    }//GEN-LAST:event_jMenuItemVerCarroComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemSesionUsuario;
    private javax.swing.JMenuItem jMenuItemVerCarroCompras;
    private javax.swing.JMenuItem jMenuItemVerProductos;
    // End of variables declaration//GEN-END:variables
}
